/**
 * B5.1 · metacognition 骨架判据测试（S1 席）
 *
 * 测真行为：用最小假 ctx 直跑 apply，断言**服务可读**（"未 provide = 没跑起来"）。
 * 运行（**禁止管道取退出码**）：cd packages/metacognition && node --test "tests/*.test.mjs"; echo $?
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const PKG = dirname(dirname(fileURLToPath(import.meta.url)))
const mod = await import(new URL('../src/index.ts', import.meta.url).href)

function fakeCtx({ withCore = true } = {}) {
  const provides = new Map()
  const listeners = []
  return {
    provides,
    listeners,
    on: (evt, fn) => listeners.push({ evt, fn }),
    get: (name) => (withCore && name === 'mana-core' ? { plugin: 'mana-core' } : undefined),
    provide: (name, svc) => {
      provides.set(name, svc)
      return () => provides.delete(name)
    },
    effect: (fn) => fn(),
  }
}

test('B5.1-⑦ metacognition 骨架：apply 提供服务，status 回报判据版本', () => {
  const ctx = fakeCtx()
  mod.apply(ctx, { criteriaEnabled: true, confidenceTarget: null })
  const svc = ctx.provides.get('mana-metacognition')
  assert.ok(svc, '未 provide mana-metacognition')
  const st = svc.status()
  assert.equal(st.plugin, 'mana-metacognition')
  assert.equal(st.wired, true)
  assert.equal(st.criteriaEnabled, true)
  assert.equal(st.criteriaVersion, mod.CRITERIA_VERSION)
})

test('B5.1-⑦ 服务面读口与直接读口一致（服务只是投影，不写第二份实现）', () => {
  const ctx = fakeCtx()
  mod.apply(ctx, { criteriaEnabled: true, confidenceTarget: null })
  const svc = ctx.provides.get('mana-metacognition')
  assert.equal(svc.threshold('activity.hotHits', -1), 23)
  assert.equal(svc.thresholdParam('activity.statusDays', 'archive', -1), 90)
  assert.deepEqual(svc.splitLaw(), { R: 1000, K: 6 })
})

test('B5.1-⑦ G9 + 依赖：注册 agent/pre-step 直通监听器；缺 core 即抛', () => {
  const ctx = fakeCtx()
  mod.apply(ctx, { criteriaEnabled: true, confidenceTarget: null })
  assert.equal(ctx.listeners.length, 1)
  assert.equal(ctx.listeners[0].evt, 'agent/pre-step')
  assert.deepEqual(mod.inject, ['mana-core'])
  assert.throws(() => mod.apply(fakeCtx({ withCore: false }), { criteriaEnabled: true, confidenceTarget: null }), /缺少 mana-core/)
})

test('B5.1-⑦ 【回归 · 走真 Config】`confidenceTarget` 不留从不生效的 null 缺省', () => {
  // 判因（本席 2026-09-24 实测 schemastery 3.18.4，非推断）：
  //   `Schema.object({p: union([number, const(null)]).default(null)})({})` → `{}`（**p 键根本不出现**），
  //   而 `Schema.number().default(0.5)` → `{x:0.5}`、`Schema.boolean().default(true)` → `{x:true}`。
  //   机制：`schemastery/src/index.ts:533-542` —— `isNullable(fallback)` 为真时直接 `return [data]`，
  //   即 **null 缺省被当作"没有缺省"**。
  //
  // ⚠ 为什么断言的是 **schema 元信息**而不是「解析结果里有没有这个键」：
  //   两者在"有 `.default(null)`"与"没有"时会得到**同一个** `{}`（已实测）——
  //   拿解析结果做判据必然**假绿**。唯一能区分二者的可读事实是
  //   `Config.dict.<key>.meta` 上是否**自有** `default` 属性（有 = 写着那个从不生效的缺省）。
  const meta = mod.Config.dict.confidenceTarget.meta
  assert.equal(
    Object.prototype.hasOwnProperty.call(meta, 'default'),
    false,
    'confidenceTarget 又带上缺省声明了 —— 若 schemastery 已修好 null 缺省，请改回 `.default(null)` 并把本条改成断言"解析后得 null"',
  )
  // 对照组：真会生效的缺省必须仍在（证明判据不是"凡缺省皆禁"）
  assert.equal(mod.Config({}).criteriaEnabled, true, 'boolean 缺省必须仍生效')
  // 显式给值仍须原样通过（不许把"除谎"做成"丢功能"）
  assert.equal(mod.Config({ confidenceTarget: 0.8 }).confidenceTarget, 0.8)
  assert.equal(mod.Config({ confidenceTarget: null }).confidenceTarget, null)
})

test('B5.1-⑦ 移植面齐备：真源/生成器/投影/读口四件都在本包内（缺一即数值不可追）', () => {
  for (const rel of ['skill/engine/criteria.json', 'scripts/gen-criteria.mjs', 'src/criteria.generated.ts', 'src/criteria.ts']) {
    assert.ok(existsSync(join(PKG, rel)), `缺 ${rel} —— 只搬 lib 会得到无法追溯的数值副本（册:555）`)
  }
  // 投影带生成器横幅（禁手写）
  assert.match(readFileSync(join(PKG, 'src', 'criteria.generated.ts'), 'utf8'), /AUTO-GENERATED by scripts\/gen-criteria\.mjs/)
})
